name: app

description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  percentages_with_animation: ^1.0.5
  flutter_swiper_view: ^1.1.8
  device_preview: ^1.2.0
  http: ^0.13.6
  flutter:
    sdk: flutter
  get: ^4.7.2
  percent_indicator: ^4.2.3
  table_calendar: ^3.0.0
  image_picker: ^0.8.6  
  permission_handler: ^11.3.0
  provider: ^6.1.4
  shared_preferences: ^2.2.2  
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  flutter_dotenv: ^5.0.2
  font_awesome_flutter: ^10.9.1
  firebase_storage: ^12.4.10
  file_picker: ^8.0.0
  url_launcher: ^6.3.0
  path_provider: ^2.1.2
  open_filex: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/logo-circulo.png
    - lib/images/flex.png
    - lib/images/individual.png
    - lib/images/pro.png
    - lib/images/nome.png
    - lib/images/sono.png
    - lib/images/refeicao.png
    - lib/images/exercicios.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo-circulo.png"